manifest:
  remotes:
    - name: Sets3n
      url-base: https://github.com/Sets3n
  projects:
    - name: zmk
      remote: Sets3n
      revision: main
      import: app/west.yml
  self:
    path: config
